# Generated by Django 4.2.11 on 2024-04-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_employee_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='regid',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
