# Generated by Django 4.2.11 on 2024-04-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_employee_regid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='regid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
